DROP PROCEDURE IF EXISTS MarkGrade;
DELIMITER //
CREATE PROCEDURE MarkGrade(IN MARK INT)
BEGIN
	DECLARE GRADE VARCHAR (1);
	IF MARK>90 THEN
		SET GRADE='S';
	ELSEIF MARK>80 THEN
		SET GRADE='A';
	ELSEIF MARK>70 THEN
		SET GRADE='B';
	ELSEIF MARK>60 THEN
		SET GRADE='C';
	ELSEIF MARK>50 THEN
		SET GRADE='D';
	ELSE
		SET GRADE='F';
	END IF;
	SELECT GRADE;
END//
DELIMITER ;
