DROP PROCEDURE IF EXISTS Greatest;
DELIMITER //
CREATE PROCEDURE Greatest(IN A INT, IN B INT, IN C INT, OUT D INT)
BEGIN
	IF A>=B AND A>=C THEN
		SET D=A;
	ELSEIF B>=C THEN
		SET D=B;
	ELSE
		SET D=C;
	END IF;
END//
DELIMITER ;
