DROP PROCEDURE IF EXISTS InvertNumber;
DELIMITER //
CREATE PROCEDURE InvertNumber(IN NUM INT)
BEGIN
	DECLARE INVERSE INT DEFAULT 0;
	DECLARE REM INT;
	WHILE NUM>0 DO
		SET REM=NUM%10;
		SET NUM=NUM DIV 10;
		SET INVERSE=(INVERSE*10)+REM;
	END WHILE;
	SELECT INVERSE;
END//
DELIMITER ;
