DROP PROCEDURE IF EXISTS SumOfN;
DELIMITER //
CREATE PROCEDURE SumOfN(IN N INT)
BEGIN
	DECLARE I INT;
	DECLARE SUM INT;
	SET I=1;
	SET SUM=0;
	WHILE I<=N DO
		SET SUM=SUM+I;
		SET I=I+1;
	END WHILE;
	SELECT SUM;
END//
DELIMITER ;
